GH-169: Implement Configure Public Client
mittwald/goharbor-client pull request #170
Opened 2023-08-07 12:36 UTC by xoanmi

Basic implementation for the `configure` client.

Close #169

2023-08-08 09:44 UTC, xoanmi commented
@elenz97 could you please check this PR?

2023-08-10 07:47 UTC, elenz97 requested changes

2023-08-10 09:05 UTC, xoanmi commented on apiv2/pkg/clients/configure/configure.go
> +	GetInternalConfigs(ctx context.Context) (*model.InternalConfigurationsResponse, error)
Removed as it is not used anyway

2023-08-10 09:56 UTC, xoanmi commented on apiv2/pkg/clients/configure/configure_integration_test.go
> +	err := c.UpdateConfigs(ctx, &modelv2.Configurations{AuthMode: authMode})
I will remove this integration test! The GetInternalConfig API is not intended to be used from users

2023-08-10 09:57 UTC, xoanmi commented on apiv2/pkg/clients/configure/configure_integration_test.go
> +	err := c.UpdateConfigs(ctx, &modelv2.Configurations{AuthMode: authMode})
Done!

2023-08-10 11:43 UTC, elenz97 requested changes

2023-08-10 11:43 UTC, elenz97 commented on apiv2/pkg/clients/configure/configure_integration_test.go
> +	err := c.UpdateConfigs(ctx, &modelv2.Configurations{AuthMode: authMode})
`authMode` still seems not be a pointer in this test :see_no_evil:

2023-08-10 11:56 UTC, xoanmi commented on apiv2/pkg/clients/configure/configure_integration_test.go
> +	err := c.UpdateConfigs(ctx, &modelv2.Configurations{AuthMode: authMode})
Sorry, I missed it. Now it should be fixed. I used the same auth_method in both tests to keep consistency

2023-08-10 12:02 UTC, elenz97 approved these changes
Looks good! Thanks for your contribution, @xoanmi

2023-08-10 12:02 UTC, merged