Add webhook policy support
mittwald/goharbor-client pull request #90
Opened 2021-04-30 08:33 UTC by shreddedbacon

I'm working on a project that requires us to be able to list, delete, add, or update webhook policies for projects.
This PR is to add support for that. It only adds it to the V2 client as this is what we're using.

Let me know if any issues. Thanks

2021-05-03 07:40 UTC, elenz97 requested changes
Hey @shreddedbacon,
thanks for the PR!

When reviewing, I found just two minor issues. Would you check?

2021-05-03 07:40 UTC, elenz97 commented on apiv2/project/project.go
> +
We should check on the WebhookPolicy object being nil here, too.
```suggestion
	if policy == nil {
		return &ErrProjectNoWebhookPolicyProvided{}
	}
```

2021-05-03 07:40 UTC, elenz97 commented on apiv2/project/project_errors.go
> +	ErrProjectNoWebhookPolicyProvidedMsg = "no project member provided"
```suggestion
	ErrProjectNoWebhookPolicyProvidedMsg = "no webhook policy provided"
```

2021-05-05 21:59 UTC, shreddedbacon commented
> Hey @shreddedbacon,
> thanks for the PR!
> 
> When reviewing, I found just two minor issues. Would you check?

Thanks for checking. I've corrected these now.

2021-05-06 07:10 UTC, elenz97 approved these changes
LGTM :+1:

2021-05-06 07:10 UTC, merged

2021-05-06 07:13 UTC, elenz97 commented
@shreddedbacon 
I've now released this with [v3.3.0](https://github.com/mittwald/goharbor-client/releases/tag/v3.3.0). Thanks for contributing!

2021-05-06 07:15 UTC, shreddedbacon commented
Thanks for the prompt release!